version: '3.4'
services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    volumes:
      - ./data:/datastore
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.changedetection.rule=Host(`changedetection.docker.local`)'
      - 'traefik.http.services.changedetection.loadbalancer.server.port=5000'
    networks:
      - proxy

networks:
  proxy:
    external: true