version: '3.4'
services:
  traefik:
    image: 'traefik:2.3'
    container_name: 'traefik'
    restart: 'unless-stopped'
    ports:
      - '80:80'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik.rule=Host(`traefik.docker.local`)'
      - 'traefik.http.services.traefik.loadbalancer.server.port=8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './traefik.toml:/traefik.toml'
    networks:
      proxy:
        ipv4_address: 172.20.0.5
networks:
  proxy:
    name: proxy
    ipam:
      config:
        - subnet: 172.20.0.0/24